[package]
name = "tide-rustls"
version = "0.0.1"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
async-std = { version = "1.6", features = ["attributes"] }
tide = { git = "https://github.com/jbr/tide", branch = "to-listener" }
async-tls = "0.7"
rustls = "0.17"
async-h1 = "2.0"
async-dup = "1.1"
