[package]
name = "tide-tls"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[dependencies]
async-std = { version = "1.6.2", features = ["attributes"] }
tide = { git = "https://github.com/jbr/tide", branch = "to-listener" }
async-tls = "0.7.0"
rustls = "0.17.0"
async-h1 = "2.0.2"
